#### Regression Model
This regression test model to predict the salary

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import numpy as np
import pickle

In [4]:
data=pd.read_csv('Dataset/Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
#Removing the unnecessary columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
#Label Encoding the categorical data - Gender
labelEncoderGender=LabelEncoder()
data['Gender']=labelEncoderGender.fit_transform(data['Gender'])
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
oneHotEncoderGeography=OneHotEncoder()
geographyEncoded=oneHotEncoderGeography.fit_transform(data[['Geography']]).toarray()
geographyEncodedDf=pd.DataFrame(geographyEncoded,columns=oneHotEncoderGeography.get_feature_names_out(['Geography']))
data=pd.concat([data.drop('Geography',axis=1),geographyEncodedDf],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [8]:
#Splitting the dataset into the Features and the Target variable
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']
X.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 12 columns]

In [9]:
#Split the dataset into the Training set and Test set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
#Feature Scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
#Save all endored in pickle file
with open('label_encoders_gender.pkl', 'wb') as f:
    pickle.dump(labelEncoderGender, f)
with open('onehot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(oneHotEncoderGeography, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

#### ANN Regression Problem Statement

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#Building the ANN
model=Sequential([
    Dense(units=64, activation='relu', input_dim=X_train.shape[1]),
    Dense(units=32, activation='relu'),
    Dense(units=1) #When activation function is not specified, it defaults to linear activation, which is suitable for regression tasks.
    ])

#compiling the ANN
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

c:\HD\AI_Projects\MachineLearningNLP\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
#Training the ANN on the Training set
import datetime
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

#Setup tensorboard
log_dir="regressionLogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [26]:
#Setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, 
                                      restore_best_weights=True)

In [27]:
#Training the ANN on the Training set
history=model.fit(X_train,y_train, validation_data=(X_test, y_test), 
                  epochs=100, 
                  callbacks=[early_stopping_callback, tensorboard_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100369.0312 - mae: 100369.0312 - val_loss: 98481.2891 - val_mae: 98481.2891
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99497.8750 - mae: 99497.8750 - val_loss: 96722.8438 - val_mae: 96722.8438
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96467.7969 - mae: 96467.7969 - val_loss: 92282.8828 - val_mae: 92282.8828
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 90593.4609 - mae: 90593.4609 - val_loss: 85064.3281 - val_mae: 85064.3281
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 82213.3125 - mae: 82213.3125 - val_loss: 76008.8750 - val_mae: 76008.8750
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 72744.2266 - mae: 72744.2266 - val_loss: 66973.1953 - val_mae: 66973.1953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 63927.6562 - mae: 63927.6562 - val_loss: 59469.2344 - val_mae: 59469.2344
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 57340.0234 - mae: 57340.0234 - val_loss: 54577.6367 - val_mae: 54577.6367
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53529.5078 - mae: 53529.5078 - val_loss: 52101.8906 - val_mae: 52101.8906
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51719.7852 - mae: 51719.7852 - val_loss: 51232.2773 - val_mae: 51232.2773
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50996.4609 - mae: 50996.4609 - val_loss: 50978.3398 - val_mae: 50978.3398
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50703.5078 - mae: 50703.5078 - val_loss: 50874.9102 - val_mae: 50874.9102
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50547.7695 - mae: 50547.7695 - val_loss: 50814.2305 - val_mae: 50814.2305
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50444.3750 - mae: 50444.3750 - val_loss: 50756.6406 - val_mae: 50756.6406
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50370.5898 - mae: 50370.5898 - val_loss: 50696.5156 - val_mae: 50696.5156
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50308.3789 - mae: 50308.3789 - val_loss: 50660.8789 - val_mae: 50660.8789
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50249.3047 - mae: 50249.3047 - val_loss: 50608.2656 - val_mae: 50608.2656
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50196.5469 - mae: 50196.5469 - val_loss: 50575.5234 - val_mae: 50575.5234
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50148.6445 - mae: 50148.6445 - val_loss: 50533.1875 - val_mae: 50533.1875
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50107.4805 - mae: 50107.4805 - val_loss: 50505.9883 - val_mae: 50505.9883
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50069.6992 - mae: 50069.6992 - val_loss: 50479.3867 - val_mae: 50479.3867
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50030.9219 - mae: 50030.9219 - val_loss: 50455.4375 - val_mae: 50455.4375
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49998.0859 - mae: 49998.0859 - val_loss: 50432.1172 - val_mae: 50432.1172
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49966.7617 - mae: 49966.7617 - val_loss: 50407.7578 - val_mae: 50407.7578
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49935.0195 - mae: 49935.0195 - val_loss: 50397.1367 - val_mae: 50397.1367
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49906.8438 - mae: 49906.8438 - val_loss: 50374.9219 - val_mae: 50374.9219
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49880.3555 - mae: 49880.3555 - val_loss: 50357.0352 - val_mae: 50357.0352
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49852.4062 - mae: 49852.4062 - val_loss: 50336.0078 - val_mae: 50336.0078
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49832.4961 - mae: 49832.4961 - val_loss: 50326.1680 - val_mae: 50326.1680
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49808.8359 - mae: 49808.8359 - val_loss: 50312.1875 - val_mae: 50312.1875
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49790.7109 - mae: 49790.7109 - val_loss: 50296.6445 - val_mae: 50296.6445
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49769.4258 - mae: 49769.4258 - val_loss: 50293.9336 - val_mae: 50293.9336
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49753.5039 - mae: 49753.5039 - val_loss: 50276.9648 - val_mae: 50276.9648
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49738.6875 - mae: 49738.6875 - val_loss: 50272.5430 - val_mae: 50272.5430
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49718.2344 - mae: 49718.2344 - val_loss: 50267.1094 - val_mae: 50267.1094
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49709.7031 - mae: 49709.7031 - val_loss: 50257.1914 - val_mae: 50257.1914
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49690.0742 - mae: 49690.0742 - val_loss: 50265.5586 - val_mae: 50265.5586
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49675.4453 - mae: 49675.4453 - val_loss: 50258.1484 - val_mae: 50258.1484
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49661.1758 - mae: 49661.1758 - val_loss: 50243.8906 - val_mae: 50243.8906
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49651.2969 - mae: 49651.2969 - val_loss: 50247.8672 - val_mae: 50247.8672
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49637.5312 - mae: 49637.5312 - val_loss: 50246.3945 - val_mae: 50246.3945
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49626.1914 - mae: 49626.1914 - val_loss: 50243.6250 - val_mae: 50243.6250
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49616.2344 - mae: 49616.2344 - val_loss: 50251.7891 - val_mae: 50251.7891
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 49600.9961 - mae: 49600.9961 - val_loss: 50247.5234 - val_mae: 50247.5234
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49593.3438 - mae: 49593.3438 - val_loss: 50244.8945 - val_mae: 50244.8945
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49580.6016 - mae: 49580.6016 - val_loss: 50247.0000 - val_mae: 50247.0000
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.9102 - mae: 49571.9102 - val_loss: 50243.6289 - val_mae: 50243.6289
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49564.3789 - mae: 49564.3789 - val_loss: 50244.5508 - val_mae: 50244.5508
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49557.9844 - mae: 49557.9844 - val_loss: 50249.0234 - val_mae: 50249.0234
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49545.6992 - mae: 49545.6992 - val_loss: 50251.1133 - val_mae: 50251.1133
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49538.7266 - mae: 49538.7266 - val_loss: 50255.8164 - val_mae: 50255.8164
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49532.8398 - mae: 49532.8398 - val_loss: 50263.5273 - val_mae: 50263.5273

In [30]:
#Load extensorboard --logdir=regressionLogs/fit
%load_ext tensorboard
%tensorboard --logdir=regressionLogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 9480), started 0:00:30 ago. (Use '!kill 9480' to kill it.)

In [31]:
## Evaluate the model on the test set
test_loss, test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE: {test_mae}')
print(f'Test Loss: {test_loss}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50243.6250 - mae: 50243.6250
Test MAE: 50243.625
Test Loss: 50243.625

In [32]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.